/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#10497a',
        'inverse-primary':          '#a0c9ff',
        'on-secondary-fixed-variant':'#004f56',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed':          '#a1eff9',
        'on-secondary-fixed':       '#001f23',
        'surface':                  '#fbf9f4',
        'surface-tint':             '#306194',
        'error-container':          '#ffdad6',
        'tertiary-fixed':           '#ffd8e8',
        'surface-container':        '#f0eee9',
        'primary-fixed-dim':        '#a0c9ff',
        'inverse-surface':          '#30312e',
        'surface-dim':              '#dbdad5',
        'on-surface':               '#1b1c19',
        'secondary':                '#006972',
        'inverse-on-surface':       '#f2f1ec',
        'on-tertiary-fixed-variant':'#84165c',
        'secondary-container':      '#9eecf6',
        'on-tertiary-container':    '#ffe5ef',
        'on-primary':               '#ffffff',
        'primary':                  '#215487',
        'surface-bright':           '#fbf9f4',
        'surface-container-highest':'#e4e2dd',
        'on-error':                 '#ffffff',
        'background':               '#fbf9f4',
        'surface-variant':          '#e4e2dd',
        'outline':                  '#727780',
        'secondary-fixed-dim':      '#85d3dd',
        'tertiary-fixed-dim':       '#ffafd5',
        'on-secondary-container':   '#0c6d76',
        'on-surface-variant':       '#42474f',
        'surface-container-high':   '#eae8e3',
        'on-background':            '#1b1c19',
        'surface-container-low':    '#f5f3ee',
        'primary-container':        '#3e6da1',
        'error':                    '#ba1a1a',
        'on-primary-fixed':         '#001c37',
        'on-secondary':             '#ffffff',
        'on-primary-container':     '#e2edff',
        'tertiary-container':       '#b13f82',
        'primary-fixed':            '#d2e4ff',
        'outline-variant':          '#c2c7d0',
        'on-error-container':       '#93000a',
        'tertiary':                 '#932568',
        'on-tertiary':              '#ffffff',
        'on-tertiary-fixed':        '#3d0027',
      },
      fontFamily: {
        headline: ['"Noto Serif Hebrew"', 'serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        '4xl':   '2.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
